(define-library (geiser complete)
  (export geiser-completions)
  (import (scheme write)
          (kawa base)
          (geiser classpath))
  (begin
    (define (java-interop-prefix? prefix :: String)
      (or (>= (invoke prefix 'indexOf ":") 0)
          (>= (invoke prefix 'indexOf ".") 0)))

    ;; Complete Java class members (methods, fields) via reflection.
    (define (complete-java-members prefix :: String)
      (let ((colon-pos (invoke prefix 'lastIndexOf ":")))
        (if (< colon-pos 0)
            '()
            (let ((class-name (invoke prefix 'substring 0 colon-pos))
                  (member-prefix (invoke prefix 'substring (+ colon-pos 1)
                                       (invoke prefix 'length))))
              (guard (exn (else '()))
                (let* ((cls :: java.lang.Class
                            (java.lang.Class:forName class-name))
                       (methods :: java.lang.reflect.Method[]
                                (cls:getMethods))
                       (fields :: java.lang.reflect.Field[]
                               (cls:getFields))
                       (candidates '()))
                  (do ((i :: int 0 (+ i 1)))
                      ((>= i (methods:length)))
                    (let* ((m :: java.lang.reflect.Method (methods i))
                           (name :: String (m:getName)))
                      (when (invoke name 'startsWith member-prefix)
                        (set! candidates
                              (cons (string-append name "("
                                    (string-join
                                     (map (lambda (p :: java.lang.Class)
                                            (p:getSimpleName))
                                          (vector->list
                                           (m:getParameterTypes)))
                                     ", ")
                                    ")")
                                    candidates)))))
                  (do ((i :: int 0 (+ i 1)))
                      ((>= i (fields:length)))
                    (let* ((f :: java.lang.reflect.Field (fields i))
                           (name :: String (f:getName)))
                      (when (invoke name 'startsWith member-prefix)
                        (set! candidates (cons name candidates)))))
                  candidates))))))

    ;; Complete Scheme symbols.
    (define (complete-symbols prefix)
      (let* ((env (interaction-environment))
             (candidates '())
             (limit 100))
        (guard (exn (else '()))
          (let ((iter (env:enumerateAllLocations)))
            (let loop ()
              (when (and (iter:hasNext) (< (length candidates) limit))
                (let* ((loc (iter:next))
                       (sym (invoke (invoke loc 'getKeySymbol) 'toString)))
                  (when (invoke sym 'startsWith prefix)
                    (set! candidates (cons sym candidates))))
                (loop)))))
        (java.util.Collections:sort candidates)
        candidates))

    (define (geiser-completions prefix)
      (if (java-interop-prefix? prefix)
          (complete-java-members prefix)
          (append (complete-symbols prefix)
                  (complete-classes prefix))))))
